title: Trusted Firmware
email: enquiries@trustedfirmware.org
description: >-
  Arm’s Trusted Firmware is adopting Open Governance and is now and Open Source project managed by Linaro.
baseurl: ""
url: "https://www.trustedfirmware.org"
markdown: kramdown
blog_images_dir: assets/images/
theme: jumbo-jekyll-theme
plugins:
  - jekyll-data
exclude:
    - .asset-cache
    - .sass-cache
    - _site
    - production.trustedfirmware.org
    - staging.trustedfirmware.org
    - Gemfile
    - Gemfile.lock
    - build-site.sh
    - check-links.sh
    - CODEOWNERS
permalink: /:categories/:title/
collections:
  authors:
    output: true
    permalink: /author/:name/
assets:
  compress:
    js: true
  autoprefixer:
    browsers: ["last 2 versions", "> 5%", "IE 9"]
  sources:
    - assets/js/
    - assets/js/vendor/
    - assets/js/app/
    - assets/images
    - assets/images/authors
    - assets/css/
    - assets/css/app
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: author
# Jekyll Pagination V2 Configuration
pagination:
  permalink: "/:num/"
  enabled: true
  per_page: 9
  trail:
    before: 2
    after: 2
  sort_reverse: true
  sort_field: "date"
